Sprint 9 1-st commit
SirBogdan/filmorate pull request #2
Opened 2022-07-14 18:01 UTC by SirBogdan

2022-07-15 16:11 UTC, kukolev requested changes

2022-07-15 16:11 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private int createNewId() {
По моему здесь этот метод лишний. Он вызывается в одном месте и выполняет только одно действие. Можно просто написать ++idCreator и не делать метод.

2022-07-15 16:11 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private int createNewId() {
По моему здесь этот метод лишний. Он вызывается в одном месте и выполняет только одно действие. Можно просто написать ++idCreator и не делать метод.

2022-07-15 18:35 UTC, SirBogdan commented
Исправил

2022-07-16 08:44 UTC, kukolev approved these changes

2022-07-16 10:46 UTC, merged