Test
SirBogdan/filmorate pull request #3
Opened 2022-08-06 19:25 UTC by SirBogdan

2022-08-11 07:27 UTC, kukolev requested changes

2022-08-11 07:27 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDbStorage.java
> +                        "SET FILM_NAME = ?, FILM_DESCRIPTION = ?, RELEASE_DATE = ?, DURATION = ?, RATE = ?, MPA_ID = ? " +
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-11 07:27 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/GenreDbStorage.java
> +        if (id <= 0 || id > 6) {
По моему эта проверка лишняя. Если жанра нет в БД, то он и не найдется в следующем запросе. Вот тогда и нужно кинуть ошибку. При этом если жанров станет 7 или более, то это условие приведет к ошибке, если его не поправить. Это лишний риск.

2022-08-11 07:27 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +        assertEquals(List.of(user3), friendsDbStorage.findFriendsIntersection(1L, 2L)); // тест метода findFriendsIntersection
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-11 09:46 UTC, SirBogdan commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/GenreDbStorage.java
> +        if (id <= 0 || id > 6) {
Александр, благодарю за ревью! Дело в том, что один из обязательных тестов проверяет запрос на получение Жанра с некорректным id и ждет ответ сервера с ошибкой 404. Предлагаемый вами вариант будет возвращать код ошибки 500 и тест не пройдет
![2022-08-11_12-43-09](https://user-images.githubusercontent.com/100284165/184107168-309f3043-7001-4630-acbc-7a7dead7f539.png)
![2022-08-11_12-42-33](https://user-images.githubusercontent.com/100284165/184107175-f7c56326-e3c2-4678-8e8f-f20af4d8a135.png)
![2022-08-11_12-39-34](https://user-images.githubusercontent.com/100284165/184107183-7df6002b-7b94-4a35-957d-66501189e9f6.png)

2022-08-11 22:23 UTC, kukolev requested changes

2022-08-11 22:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/GenreDbStorage.java
> +        if (id <= 0 || id > 6) {
Богдан, все верно, тест должен пройти. При этом все равно можно и нужно убрать проверку. Просто киньте исключение ObjectNotFoundException если запрос к БД не вернул результатов. Сейчас вы кидаете исключение, опираясь на некоторые знания об id, что он должен быть в некотором диапазоне. Будет лучше, если исключение будет выбрасываться на основании объективных данных, полученных из БД.

2022-08-12 21:51 UTC, kukolev requested changes

2022-08-12 21:51 UTC, kukolev commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:h2:file:./db/filmorate
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-12 21:51 UTC, kukolev commented on src/main/resources/application.properties
> +#spring.jpa.hibernate.ddl-auto=update
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-12 21:51 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    public void userDbStorageTest() {
Этот тест и тесты лучше разбить на несколько, т.к. они сейчас слишком большие и охватывают несколько кейсов. Лучше сделать много тестов, но небольших. Тогда будет проще понять что пошло не так, если упадет несколько тестов, каждый из которых посвящен только своему функционалу.

2022-08-16 06:23 UTC, kukolev approved these changes

2022-08-16 09:10 UTC, merged